### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by mathiasbynens** [tadeusrox/tibia_maps#1]
This repository is a straight-up copy of the code generated by https://github.com/tibiamaps/tibia-map, with the license (MIT) and all attribution stripped.

Not cool.

**Comment by tadeusrox** [comment]
@mathiasbynens I did not know about the license I added from tibiamaps on this commit https://github.com/tadeusrox/tibia_maps/commit/945a63124ccc7ddafa0e07e96205001108d838b3 

Is there any other thing that I should do?
